FoundationAgents/OpenManus

app/config.py, app/llm.py, config/config.example.toml
=> # feat: AzureOpenaIAPI support

main.py
=> remove empty prompt

README.md, README_tw.md
- Update language links in the README to include Traditional and Simplified Chinese options
- Remove outdated HTML paragraph tags from the README
- Add a new README file in Traditional Chinese
- Include installation instructions and configuration steps in the new README
- Add a video demonstration section in the new README
- Enhance the roadmap section with additional planning items in both README files
- Encourage community engagement and contributions in both README files
=> docs: enhance README with multilingual support and community engagement

README.md, README_zh.md, main.py
- Add support for 'quit' command alongside 'exit'
- Update input prompt to show both exit options
- Enhance empty input handling to catch both empty strings and whitespace
- Replace isspace() check with more robust empty string validation
- Optimize command checking by storing lowercase result
- Improve code readability and user experience
=> feat: improve input handling

app.py, config/config.toml, run.bat, static/main.js, static/style.css, templates/index.html
=> 未改变源程序，仅提供输入输出界面展示

requirements.txt
add fastapi version  in requirements.txt
=> add fastapi version  in requirements.txt

app.py, static/main.js, static/style.css
**Features**
- Feature 1
- Feature 2
**Influence**
**Result**
**Other**
=> modified by hook

README.md, README_ko.md, README_zh.md
**Features**
- Added Korean translation file
- Introduced a dropdown menu to easily switch between available languages in README files
- Included links to English (`README.md`), Chinese (`README_zh.md`), and Korean (`README_ko.md`) versions
- Dropdown menu implementation for language selection in README files  
**Influence**
- Korean users can now easily access translated content  
- Language dropdown improves the usability and navigation for multilingual users  
- Suggested structure can be extended to additional languages in the future  
**Result**
- Korean users can now easily access translated content  
- Language dropdown improves the usability and navigation for multilingual users  
- Suggested structure can be extended to additional languages in the future
=> docs: add Korean README file

app/tool/terminal.py
**Features**
Enhanced the Terminal tool with better command output handling
=> add a new tool called terminal

app.py, run.bat, static/main.js
**Features**
- Feature 1
- Feature 2
**Influence**
**Result**
**Other**
=> fix download bug

app/tool/python_execute.py
[**Features**
[issue](https://github.com/mannaandpoem/OpenManus/issues/541)
- running the following code will led to resource leakage， such as memory 
`
data = []
while True:
print("this is while function")
data.append("this is while function")
`
we can use multiprocessing solve it according this pull request.
=> update python_execute thread safe

app/llm.py
**Features**
- Support OpenAI Reasoning Models (o1, o3-mini)
- Modified the code to fit the parameters of OpenAI's Reasoning Models
fix: #411 
close: #423
=> Support OpenAI Reasoning Models (o1, o3-mini)

config/config.example.toml
**Features**
- Add config support for Ollama
=> Add config support for Ollama

app/tool/web_search.py
**Features**
- Fix #591 
- Fix #218 
**Influence**
- web_search.py
**Result**
-
**Other**
-
=> refactor(web_search): enhance web search functionality with engine fallback

.gitignore
**Features**
File config.toml includes credential, like API key of model and proxy password. So it's better to add it to .gitignore and avoid uploading it to any git repository by incidence.
File config.toml is also a customized file for developers. Adding it to ignore list would help developers to stash it eah time before publish changes to this project.
=> bug fix: update .gitignore to include config/config.toml for sensitive information

Dockerfile
**Features**
- add Dockerfile and start.sh (for init)
**Influence**
- simple make docker-image by Dockerfile
**Result**
- added dockerfile
- added start.sh
**Other**
=> add docker file and start.sh

.github/workflows/environment-corrupt-check.yaml, .github/workflows/pr-autodiff.yaml
**Features**
- Feature 1
- Feature 2
**Influence**
**Result**
**Other**
=> chore: update Python version to latest ones

.github/workflows/pr-autodiff.yaml
Updated pr-autodiff.yaml to use newer versions of github actions
=> Updated pr-autodiff.yaml to use newer versions of github actions

app/llm.py, app/tool/file_saver.py
**Features**
- print the token used information, the change with filesaver file is just for pass the pre commit check.(isort)
**the token used information**
=> print the token used information 

app/tool/search/__init__.py, app/tool/search/bing_search.py, app/tool/web_search.py
This PR adds support for Bing Search to the project. 
The previous review was approved and the conflicts were resolved. I then re-established a branch for modification.
=> add bing search

app.py, static/main.js, static/style.css, templates/index.html
Add page LLM configuration settings
=> Front endAdd page LLM configuration settings

app/tool/browser_use_tool.py
**Features**
- reimplement screenshot logics to get JPEG data
=> fix(browser_use_tool): reimplement screenshot logics to get JPEG data

app/bedrock.py, app/llm.py, config/config.example.toml, requirements.txt
**Features**
- Added modular and non-intrusive Amazon Bedrock support
- Maintained compatibility with existing codebase through non-intrusive design pattern
- Fix this https://github.com/mannaandpoem/OpenManus/issues/215
https://docs.aws.amazon.com/bedrock/latest/APIReference/welcome.html
**Influence**
This PR introduces Amazon Bedrock support as a modular component that can be easily integrated without disrupting existing functionality. The implementation follows a non-intrusive approach, allowing users to opt-in to Bedrock services while maintaining backward compatibility. The changes are isolated to minimize impact on the core codebase while providing full access to Amazon Bedrock's capabilities.
**Result**
**Other**
1. Supporting Amazon Bedrock can significantly …
=> Add Amazon Bedrock support modular non-intrusive 

config/config.example.toml
**Features**
- Feature 1
- Feature 2
**Influence**
**Result**
**Other**
=> 删除合并冲突提示代码

app/agent/browser.py, app/agent/toolcall.py
**Features**
- issue 1: 修复Manus即使任务已完成也会一直循环到max_steps才停止的问题
- issue 2: 修复Manus没有使用`browse-use`工具，但Masus.next_step_prompt被意外设置成`app.prompt.browser.NEXT_STEP_PROMPT`的问题
问题分析：
**问题1**:
类的继承关系：`Manus` -> `BrowserAgent` -> `ToolCallAgent` -> `ReActAgent`
在`ToolCallAgent.think()`的实现https://github.com/mannaandpoem/OpenManus/blob/a10b9734944db54c55c4befd3c9b7b56fdddab46/app/agent/toolcall.py#L116-L118
对于以下两种情况：
1. 用户提问是简单任务，例如“你是谁”，“你有哪些工具”
2. 用户提问需要调用工具，且工具已调用完成，达到最后总结
此时`self.tool_calls is None，content is not None`，导致ToolCallAgent.think()恒为true，以下代码判断should_act恒为true，最后一直循环act，直至达到最大循环次数max_steps
https://github.com/mannaandpoem/OpenManus/blob/a10b9734944db54c55c4befd3c9b7b56fdddab46/app/agent/react.py#L33-L38
**问题2**: …
=> fix: infinite loop in simple question until max_step is reached

app/tool/browser_use_tool.py
**Features**
as title the gpt4o and claude3 maybe max token desc this patch simple the prompt
close #787
=> fix: simple browser use tool desc for gpt4o max len close #787

app/config.py, app/tool/search/baidu_search.py, app/tool/search/base.py, app/tool/search/bing_search.py, app/tool/search/duckduckgo_search.py, app/tool/search/google_search.py, app/tool/web_search.py, config/config.example.toml, requirements.txt
Add type hint for WebSearch and update SearchSettings
=> update WebSearch and SearchSettings

desktop/frontend/src/assets/css/main.css, desktop/frontend/src/components/TopHeader.vue, desktop/frontend/src/locales/en.js, desktop/frontend/src/locales/zh-cn.js, desktop/frontend/src/views/Home.vue, desktop/frontend/src/views/config/Init.vue, desktop/frontend/src/views/task/TaskIndex.vue
**Features**
- Improve home page
- Improve task page
**Influence**
**Result**
**Other**
=> Desktop: Improve home page and task page

app/prompt/browser.py, app/prompt/manus.py
**Features**
- Feature 1
- Feature 2
**Influence**
**Result**
**Other**
=> add terminate for NEXT_STEP_PROMPT in browser & manus

config/config.example-model-ppio.toml
**Features**
- Add config example for PPIO
=> feat: add config example for PPIO

app/agent/toolcall.py
=> delete duplicate code

app/agent/mcp.py, app/tool/mcp.py
**Features**
About McpAgent session bug
=> BUGFIX: FIX MCPAgent Bug

app/tool/chart_visualization/package-lock.json
**Fix**
Fix wrong resolved url in package-lock.json. Transfer to npmjs url.
**Features**
**Influence**
**Result**
**Other**
=> fix: fix wrong resolved url in pacakge-lock.json
